org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

mod_id=xpdemagnetization
mod_name=XP Demagnetization
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.npg418
mod_authors=NPG418
mod_description=Demagnetize your XP Orbs!
